apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jenkins-go-demo
  namespace: kube-ops
spec:
  template:
    metadata:
      labels:
        app: jenkins-go-demo
    spec:
      containers:
      - image: fzhydocker/go:<BUILD_TAG>
        imagePullPolicy: IfNotPresent
        name: jenkins-go-demo
        env:
        - name: branch
          value: <BRANCH_NAME>
